#!/usr/bin/env node
/**
 * Unit tests for verify-sa-output.js.
 * Zero deps: run with `node verify-sa-output.test.js`.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const SCRIPT = path.join(__dirname, 'verify-sa-output.js');
const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'verify-sa-output-test-'));

let passed = 0, failed = 0;
function test(name, fn) {
  try { fn(); console.log(`  ok  ${name}`); passed++; }
  catch (e) { console.error(`  FAIL ${name}\n       ${e.message}`); failed++; }
}
function assert(cond, msg) { if (!cond) throw new Error(msg || 'assertion failed'); }

let counter = 0;
const OVERVIEW = 'graph TB\n  A[Frontend] --> B[Service]\n';
const DETAILED = 'flowchart LR\n  A -->|calls| B\n';
const PLATFORM_OK = [
  '# Platform', '',
  '## Architecture Diagram', '',
  '- [diagrams/architecture-overview.mmd](./diagrams/architecture-overview.mmd) — high-level',
  '- [diagrams/architecture.mmd](./diagrams/architecture.mmd) — detailed', '',
].join('\n');

// Build a context dir; overrides let each test perturb one artifact.
function makeContext({ overview = OVERVIEW, detailed = DETAILED, platform = PLATFORM_OK, omit } = {}) {
  const ctx = path.join(TMP, `ctx-${counter++}`);
  fs.mkdirSync(path.join(ctx, 'diagrams'), { recursive: true });
  if (omit !== 'overview') fs.writeFileSync(path.join(ctx, 'diagrams', 'architecture-overview.mmd'), overview);
  if (omit !== 'detailed') fs.writeFileSync(path.join(ctx, 'diagrams', 'architecture.mmd'), detailed);
  if (omit !== 'platform') fs.writeFileSync(path.join(ctx, 'platform.md'), platform);
  return ctx;
}
function run(ctx) { return spawnSync('node', [SCRIPT, ctx], { encoding: 'utf8' }); }

console.log('\nverify-sa-output tests\n');

test('happy path → exit 0', () => {
  const r = run(makeContext());
  assert(r.status === 0, `expected 0, got ${r.status}: ${r.stderr}`);
});

test('missing a diagram → exit 1', () => {
  const r = run(makeContext({ omit: 'detailed' }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/missing diagram/.test(r.stderr), r.stderr);
});

test('empty diagram → exit 1', () => {
  const r = run(makeContext({ overview: '   \n' }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/empty diagram/.test(r.stderr), r.stderr);
});

test('leftover markdown fence in diagram → exit 1', () => {
  const r = run(makeContext({ overview: '```mermaid\ngraph TB\n  A --> B\n```\n' }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/code fence/.test(r.stderr), r.stderr);
});

test('non-mermaid first line → exit 1', () => {
  const r = run(makeContext({ overview: 'this is not a diagram\n  A --> B\n' }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/not a recognized Mermaid/.test(r.stderr), r.stderr);
});

test('mermaid %% comment before header is tolerated → exit 0', () => {
  const r = run(makeContext({ overview: '%% generated by /discover\ngraph LR\n  A --> B\n' }));
  assert(r.status === 0, `expected 0, got ${r.status}: ${r.stderr}`);
});

test('platform.md with inline ```mermaid → exit 1', () => {
  const bad = PLATFORM_OK + '\n```mermaid\ngraph TB\n  A --> B\n```\n';
  const r = run(makeContext({ platform: bad }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/inline ```mermaid|inline/.test(r.stderr), r.stderr);
});

test('platform.md missing a pointer link → exit 1', () => {
  const bad = PLATFORM_OK.replace(/.*architecture\.mmd.*\n/, '');
  const r = run(makeContext({ platform: bad }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/does not reference diagrams\/architecture\.mmd/.test(r.stderr), r.stderr);
});

test('missing platform.md → exit 1', () => {
  const r = run(makeContext({ omit: 'platform' }));
  assert(r.status === 1, `expected 1, got ${r.status}`);
  assert(/missing platform\.md/.test(r.stderr), r.stderr);
});

test('dotted-edge label with a period → warning (exit 2)', () => {
  const r = run(makeContext({ detailed: 'flowchart LR\n  A -.v1.2.-> B\n' }));
  assert(r.status === 2, `expected 2 (warn), got ${r.status}: ${r.stderr}`);
  assert(/dotted-edge/.test(r.stderr), r.stderr);
});

test('no arg → exit 1 (usage)', () => {
  const r = spawnSync('node', [SCRIPT], { encoding: 'utf8' });
  assert(r.status === 1, `expected 1, got ${r.status}`);
});

fs.rmSync(TMP, { recursive: true, force: true });
console.log(`\n${passed} passed, ${failed} failed\n`);
process.exit(failed ? 1 : 0);
